# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1649, 950)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open = QtWidgets.QPushButton(self.centralwidget)
        self.open.setGeometry(QtCore.QRect(180, 840, 131, 51))
        self.open.setObjectName("open")
        self.end = QtWidgets.QPushButton(self.centralwidget)
        self.end.setGeometry(QtCore.QRect(580, 840, 131, 51))
        self.end.setObjectName("end")
        self.original = QtWidgets.QLabel(self.centralwidget)
        self.original.setGeometry(QtCore.QRect(20, 30, 769, 769))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.original.setFont(font)
        self.original.setObjectName("original")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(410, 840, 111, 51))
        self.start.setObjectName("start")
        self.process = QtWidgets.QLabel(self.centralwidget)
        self.process.setGeometry(QtCore.QRect(820, 30, 769, 769))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.process.setFont(font)
        self.process.setObjectName("process")
        self.cart = QtWidgets.QRadioButton(self.centralwidget)
        self.cart.setGeometry(QtCore.QRect(770, 830, 111, 31))
        self.cart.setObjectName("cart")
        self.paint = QtWidgets.QRadioButton(self.centralwidget)
        self.paint.setGeometry(QtCore.QRect(770, 860, 111, 31))
        self.paint.setObjectName("paint")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(900, 830, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(900, 870, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.brightness = QtWidgets.QSlider(self.centralwidget)
        self.brightness.setGeometry(QtCore.QRect(1000, 840, 301, 21))
        self.brightness.setOrientation(QtCore.Qt.Horizontal)
        self.brightness.setObjectName("brightness")
        self.saturation = QtWidgets.QSlider(self.centralwidget)
        self.saturation.setGeometry(QtCore.QRect(1000, 870, 301, 21))
        self.saturation.setOrientation(QtCore.Qt.Horizontal)
        self.saturation.setObjectName("saturation")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1649, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open.setText(_translate("MainWindow", "Open Carema"))
        self.end.setText(_translate("MainWindow", "End"))
        self.original.setText(_translate("MainWindow", "carema"))
        self.start.setText(_translate("MainWindow", "Start"))
        self.process.setText(_translate("MainWindow", "generalized"))
        self.cart.setText(_translate("MainWindow", "Cartoonize"))
        self.paint.setText(_translate("MainWindow", "Painting-style"))
        self.label.setText(_translate("MainWindow", "brightness"))
        self.label_2.setText(_translate("MainWindow", "saturation"))
